spring:
  data:
    redis:
      password: 123456789
      database: 1
      host: 192.168.227.130
      port: 6379

music:
  wyy:
    serviceUrl: "http://chrelyonly-wyy-music-system:3000"
  kg:
    serviceUrl: "http://chrelyonly-kg-music-system:3000"
  qq:
    serviceUrl: "http://chrelyonly-qq-music-system:3200"
