spring:
  data:
    redis:
      password: 123456789
      database: 1
      host: 192.168.1.111
      port: 6379

music:
  wyy:
    serviceUrl: "http://127.0.0.1:3000"
  kg:
    serviceUrl: "http://127.0.0.1:3000"
