spring:
  data:
    redis:
      ##redis 单机环境配置
      host: ${chrelyonly.dev.host}
      port: 16379
      password: 123456789
      database: 6
      ssl:
        enabled: false

music:
  wyy:
    serviceUrl: "http://127.0.0.1:3000"
  kg:
    serviceUrl: "http://127.0.0.1:3000"
  qq:
    serviceUrl: "http://127.0.0.1:3200"
